# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.contact.contact_mailer:
        class: AppBundle\Contact\ContactMailer
        arguments:
            - '@twig'
            - '@mailer'
            - '%mailer_from%'
            - '%mailer_to%'
